#!/usr/bin/env node
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Regenerates frontend/src/wordlists/fr.ts from Lexique 3.83 (CC BY-SA 4.0, www.lexique.org).
// Usage: node tools/wordlists/build-fr.mjs Lexique383.tsv
// Source: http://www.lexique.org/databases/Lexique383/Lexique383.tsv
// SHA-256 of the source used: 637ba37a767a66679c48371d673ece50cbf541b49a4e40e598963d4f3fbce52b
//
// Selection (spec §5.1: at least 2048 words, no homophones nor ambiguous words, dictatable):
// - common nouns and adjectives in their dictionary form (lemma, not plural);
// - 4 to 8 letters a–z only: no accent, hyphen, apostrophe or space to type or spell out; no
//   "oe" (typed "œ"), no w, k or y and no English spelling patterns (sh, ee, oo, ea not "eau");
// - no word pronounced like another lemma of Lexique ("mer", "mère", "maire"), comparing
//   pronunciations most speakers merge (è/é, open/closed o, the eu sounds, in/un);
// - not in tools/wordlists/fr-exclude.txt;
// - no two words one letter apart (substitution, insertion, deletion): the more frequent stays;
// - the 4096 most frequent remaining words (films and books), sorted alphabetically.
// Six words give 72 bits (spec: at least 66).

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';

const SIZE = 4096;
const SOURCE_SHA256 = '637ba37a767a66679c48371d673ece50cbf541b49a4e40e598963d4f3fbce52b';

const source = readFileSync(process.argv[2] ?? '');
if (createHash('sha256').update(source).digest('hex') !== SOURCE_SHA256) throw new Error('Unexpected Lexique file (SHA-256)');
const [header, ...rows] = source.toString('utf8').split('\n').filter((line) => line !== '');
const column = Object.fromEntries(header.split('\t').map((name, index) => [name, index]));
const records = rows.map((line) => line.split('\t'));

// Pronunciations most speakers do not distinguish (Lexique phonetic alphabet).
const merged = (phon) => phon.replace(/E/g, 'e').replace(/O/g, 'o').replace(/[29°]/g, '2').replace(/1/g, '5');

// Every lemma pronounced the same way, over the whole lexicon: a word's own inflections
// ("chat", "chats") are not homophones, other lemmas are ("verre", "vert", "ver").
const lemmas = new Map();
for (const r of records) {
  const key = merged(r[column.phon]);
  const set = lemmas.get(key) ?? new Set();
  set.add(r[column.lemme]);
  lemmas.set(key, set);
}
const excluded = new Set(readFileSync(new URL('./fr-exclude.txt', import.meta.url), 'utf8').split('\n').map((l) => l.trim()).filter((l) => l !== '' && !l.startsWith('#')));

const score = new Map();
for (const r of records) {
  const word = r[column.ortho];
  if (!['NOM', 'ADJ'].includes(r[column.cgram]) || r[column.islem] !== '1' || word !== r[column.lemme] || r[column.nombre] === 'p') continue;
  if (!/^[a-z]{4,8}$/.test(word) || /oe|[wky]|sh|ee|oo|ea(?!u)/.test(word) || excluded.has(word)) continue;
  if ((lemmas.get(merged(r[column.phon]))?.size ?? 0) > 1) continue;
  const frequency = Math.max(Number(r[column.freqlemfilms2]) || 0, Number(r[column.freqlemlivres]) || 0);
  score.set(word, Math.max(score.get(word) ?? 0, frequency));
}
// A word also listed under another pronunciation (homograph) is ambiguous when read aloud.
const pronunciations = new Map();
for (const r of records) {
  if (!score.has(r[column.ortho])) continue;
  const set = pronunciations.get(r[column.ortho]) ?? new Set();
  set.add(r[column.phon]);
  pronunciations.set(r[column.ortho], set);
}
const candidates = [...score.entries()]
  .filter(([word]) => (pronunciations.get(word)?.size ?? 0) === 1)
  .sort(([a, x], [b, y]) => y - x || (a < b ? -1 : 1));
// Greedy by frequency: a word one edit away from an already kept word is dropped.
const ALPHABET = 'abcdefghijklmnopqrstuvwxyz';
const neighbours = function* (word) {
  for (let i = 0; i <= word.length; i++) {
    if (i < word.length) yield word.slice(0, i) + word.slice(i + 1);
    for (const c of ALPHABET) {
      yield word.slice(0, i) + c + word.slice(i);
      if (i < word.length && c !== word[i]) yield word.slice(0, i) + c + word.slice(i + 1);
    }
  }
};
const kept = new Set();
for (const [word] of candidates) {
  if (kept.size === SIZE) break;
  let close = false;
  for (const other of neighbours(word)) {
    if (kept.has(other)) {
      close = true;
      break;
    }
  }
  if (!close) kept.add(word);
}
if (kept.size < SIZE) throw new Error(`Only ${kept.size} words after the filters`);
const words = [...kept].sort();
if (new Set(words).size !== SIZE) throw new Error('Duplicate words');

writeFileSync(
  new URL('../../frontend/src/wordlists/fr.ts', import.meta.url),
  `// SPDX-License-Identifier: CC-BY-SA-4.0\n/*! French passphrase word list derived from Lexique 3.83 (Boris New, Christophe Pallier et al.,\n * www.lexique.org), @license CC-BY-SA-4.0 (https://creativecommons.org/licenses/by-sa/4.0/).\n * Generated by tools/wordlists/build-fr.mjs (selection rules there); do not edit. */\n\nconst words: string[] = ${JSON.stringify(words)};\nexport default words;\n`,
);
console.log(`${words.length} words from ${candidates.length} candidates`);
