#!/usr/bin/env node
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Regenerates frontend/src/wordlists/en.ts from the EFF large word list (CC BY 3.0 US).
// Usage: node tools/wordlists/build-en.mjs eff_large_wordlist.txt
// Source: https://www.eff.org/files/2016/07/18/eff_large_wordlist.txt

import { readFileSync, writeFileSync } from 'node:fs';

const words = readFileSync(process.argv[2], 'utf8').split('\n').filter((l) => l.includes('\t')).map((l) => l.split('\t')[1].trim());
if (words.length !== 7776 || new Set(words).size !== 7776) throw new Error('Unexpected word list');
writeFileSync(
  new URL('../../frontend/src/wordlists/en.ts', import.meta.url),
  `// SPDX-License-Identifier: CC-BY-3.0-US\n// EFF Large Wordlist for Passphrases (https://www.eff.org/dice), 7776 words, CC BY 3.0 US.\n// Generated by tools/wordlists/build-en.mjs from the published file; do not edit.\n\nconst words: string[] = ${JSON.stringify(words)};\nexport default words;\n`,
);
