<?php

// SPDX-License-Identifier: AGPL-3.0-or-later

declare(strict_types=1);

namespace QuietLink\Theme;

use InvalidArgumentException;
use QuietLink\Config\InstanceConfig;
use QuietLink\Maintenance\ThemeBuilder;
use QuietLink\Storage\AtomicFile;

/**
 * Compiles the operator token file (config/themes/<file>.json) into a static, hashed CSS file
 * in storage.generated_assets_dir (§6.5, ADR-0003). Only allowlisted tokens and value types
 * are accepted; nothing is ever injected inline.
 */
final class TokenThemeBuilder implements ThemeBuilder
{
    public const MANIFEST = 'tokens.json';

    private const COLOR_TOKENS = [
        'color-background', 'color-surface', 'color-surface-accent', 'color-text', 'color-text-muted',
        'color-border', 'color-border-control', 'color-primary', 'color-primary-hover',
        'color-primary-contrast', 'color-primary-text', 'color-focus',
    ];

    /** Length tokens with their allowed range in rem (px divided by 16). */
    private const LENGTH_TOKENS = [
        'radius' => [0.0, 2.0],
        'radius-small' => [0.0, 1.0],
        'space' => [0.5, 2.0],
        'font-size' => [1.0, 1.5],
        'content-width' => [30.0, 80.0],
    ];

    public function __construct(private readonly string $configDir)
    {
    }

    public function build(InstanceConfig $config): void
    {
        $dir = $config->storage->generatedAssetsDir;
        $manifest = $dir . '/' . self::MANIFEST;
        $file = $config->theme->customTokensFile;
        if ($file === null) {
            AtomicFile::write($manifest, (string) json_encode(['file' => null]));

            return;
        }
        $json = @file_get_contents($this->configDir . '/themes/' . $file);
        $data = $json === false ? null : json_decode($json, true);
        if (!is_array($data)) {
            throw new InvalidArgumentException('The theme token file is not valid JSON.');
        }
        $css = self::compile($data);
        $name = 'tokens.' . substr(hash('sha256', $css), 0, 16) . '.css';
        if (!is_file($dir . '/' . $name)) {
            AtomicFile::write($dir . '/' . $name, $css);
            @chmod($dir . '/' . $name, 0644);
        }
        AtomicFile::write($manifest, (string) json_encode(['file' => $name]));
        @chmod($manifest, 0644);
    }

    /**
     * @param array<array-key, mixed> $data {"light": {token: value}, "dark": {token: value}}
     */
    public static function compile(array $data): string
    {
        $unknown = array_diff(array_map('strval', array_keys($data)), ['light', 'dark']);
        if ($unknown !== []) {
            throw new InvalidArgumentException('Theme files only contain "light" and "dark" sections.');
        }
        $light = self::declarations($data['light'] ?? []);
        $dark = self::declarations($data['dark'] ?? []);
        $css = "/* Generated by app:boot from the operator token file. */\n";
        if ($light !== '') {
            $css .= ":root {\n{$light}}\n";
        }
        if ($dark !== '') {
            $css .= "@media (prefers-color-scheme: dark) {\n  :root:not([data-theme=\"light\"]) {\n{$dark}  }\n}\n:root[data-theme=\"dark\"] {\n{$dark}}\n";
        }

        return $css;
    }

    private static function declarations(mixed $tokens): string
    {
        if (!is_array($tokens)) {
            throw new InvalidArgumentException('Theme sections must be objects.');
        }
        $lines = '';
        foreach ($tokens as $name => $value) {
            $name = (string) $name;
            if (!is_string($value)) {
                throw new InvalidArgumentException(sprintf('Token "%s" must be a string.', $name));
            }
            if (in_array($name, self::COLOR_TOKENS, true)) {
                if (preg_match('/^#[0-9a-fA-F]{6}$/D', $value) !== 1) {
                    throw new InvalidArgumentException(sprintf('Token "%s" must be a #rrggbb colour.', $name));
                }
            } elseif (isset(self::LENGTH_TOKENS[$name])) {
                if (preg_match('/^(\d+(?:\.\d+)?)(rem|px)$/D', $value, $match) !== 1) {
                    throw new InvalidArgumentException(sprintf('Token "%s" must be a length in rem or px.', $name));
                }
                $rem = $match[2] === 'px' ? (float) $match[1] / 16 : (float) $match[1];
                [$min, $max] = self::LENGTH_TOKENS[$name];
                if ($rem < $min || $rem > $max) {
                    throw new InvalidArgumentException(sprintf('Token "%s" is out of range.', $name));
                }
            } else {
                throw new InvalidArgumentException(sprintf('Token "%s" is not customisable.', $name));
            }
            $lines .= sprintf("  --ql-%s: %s;\n", $name, strtolower($value));
        }

        return $lines;
    }

    /**
     * Public URL of the generated token stylesheet, or null.
     */
    public static function stylesheet(InstanceConfig $config): ?string
    {
        $json = @file_get_contents($config->storage->generatedAssetsDir . '/' . self::MANIFEST);
        $data = $json === false ? null : json_decode($json, true);
        $file = is_array($data) ? ($data['file'] ?? null) : null;

        return is_string($file) && preg_match('/^tokens\.[0-9a-f]{16}\.css$/D', $file) === 1 ? '/themes/generated/' . $file : null;
    }
}
