<?php

// SPDX-License-Identifier: AGPL-3.0-or-later

declare(strict_types=1);

namespace QuietLink\Tests\Support;

use RuntimeException;

/**
 * Loads the shared sp-proto/v1 test vectors (tests/vectors/sp-proto-v1.json).
 *
 * The file is generated by tools/vectors/generate-sp-proto-v1.mjs and shared
 * by the backend, the frontend and the CLI. It contains dummy values only.
 */
final class SpProtoV1Vectors
{
    public const PATH = __DIR__ . '/../vectors/sp-proto-v1.json';

    /** @var array<string, mixed>|null */
    private static ?array $document = null;

    /**
     * @return array<string, mixed>
     */
    public static function document(): array
    {
        if (self::$document === null) {
            $json = file_get_contents(self::PATH);
            if ($json === false) {
                throw new RuntimeException('Unable to read the sp-proto/v1 vector file.');
            }
            $decoded = json_decode($json, true, 512, JSON_THROW_ON_ERROR);
            if (!is_array($decoded)) {
                throw new RuntimeException('The sp-proto/v1 vector file must contain a JSON object.');
            }
            /** @var array<string, mixed> $decoded */
            self::$document = $decoded;
        }

        return self::$document;
    }

    /**
     * Returns the vectors of one group, keyed by vector name, for use as a data provider.
     *
     * @return array<string, array{array<string, mixed>}>
     */
    public static function group(string $name): array
    {
        $groups = self::document()['groups'] ?? null;
        if (!is_array($groups) || !isset($groups[$name]) || !is_array($groups[$name])) {
            throw new RuntimeException(sprintf('Unknown vector group "%s".', $name));
        }

        $cases = [];
        foreach ($groups[$name] as $vector) {
            $vectorName = is_array($vector) ? ($vector['name'] ?? null) : null;
            if (!is_array($vector) || !is_string($vectorName)) {
                throw new RuntimeException(sprintf('Malformed vector in group "%s".', $name));
            }
            /** @var array<string, mixed> $vector */
            $cases[$vectorName] = [$vector];
        }

        return $cases;
    }

    /**
     * Reads a string at a dotted path (e.g. "expected.k_enc") of a vector.
     *
     * @param array<string, mixed> $vector
     */
    public static function string(array $vector, string $path): string
    {
        $value = self::value($vector, $path);
        if (!is_string($value)) {
            throw new RuntimeException(sprintf('Vector field "%s" is not a string.', $path));
        }

        return $value;
    }

    /**
     * Reads a lowercase hex field and returns the raw bytes.
     *
     * @param array<string, mixed> $vector
     */
    public static function bytes(array $vector, string $path): string
    {
        $bytes = hex2bin(self::string($vector, $path));
        if ($bytes === false) {
            throw new RuntimeException(sprintf('Vector field "%s" is not valid hex.', $path));
        }

        return $bytes;
    }

    /**
     * @param array<string, mixed> $vector
     */
    public static function int(array $vector, string $path): int
    {
        $value = self::value($vector, $path);
        if (!is_int($value)) {
            throw new RuntimeException(sprintf('Vector field "%s" is not an integer.', $path));
        }

        return $value;
    }

    /**
     * @param array<string, mixed> $vector
     */
    public static function value(array $vector, string $path): mixed
    {
        $current = $vector;
        foreach (explode('.', $path) as $segment) {
            if (!is_array($current) || !array_key_exists($segment, $current)) {
                throw new RuntimeException(sprintf('Vector field "%s" is missing.', $path));
            }
            $current = $current[$segment];
        }

        return $current;
    }
}
