#!/usr/bin/env node
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Requirement coverage report (§0.2, §16.4): crosses docs/traceability.md with the
// requirement identifiers cited by the automated tests (PHPUnit #[Group], Vitest and
// Playwright "Requirements:" headers, vector groups). Output: docs/coverage.md.
// Usage: node tools/traceability/coverage.mjs [--check]

import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const root = new URL('../..', import.meta.url).pathname;
const matrix = readFileSync(join(root, 'docs/traceability.md'), 'utf8');
const requirements = [];
for (const line of matrix.split('\n')) {
  const cells = line.split('|').map((c) => c.trim());
  if (/^EXG-[A-Z0-9]+-\d{3}$/.test(cells[1] ?? '')) {
    requirements.push({ id: cells[1], section: cells[2], summary: cells[3], priority: cells[4], planned: cells[6] ?? '' });
  }
}

function files(dir, pattern, out = []) {
  for (const name of readdirSync(dir)) {
    const path = join(dir, name);
    if (statSync(path).isDirectory()) files(path, pattern, out);
    else if (pattern.test(name)) out.push(path);
  }
  return out;
}

const cited = new Map();
const cite = (id, where) => {
  if (!cited.has(id)) cited.set(id, new Set());
  cited.get(id).add(where);
};
const sources = [
  ...files(join(root, 'tests'), /\.php$/),
  ...files(join(root, 'frontend/tests'), /\.test\.ts$/),
  ...files(join(root, 'tests/e2e'), /\.spec\.ts$/),
];
for (const file of sources) {
  const text = readFileSync(file, 'utf8');
  for (const match of text.matchAll(/EXG-[A-Z0-9]+-\d{3}/g)) cite(match[0], relative(root, file));
}
const vectors = JSON.parse(readFileSync(join(root, 'tests/vectors/sp-proto-v1.json'), 'utf8'));
for (const ids of Object.values(vectors.requirements ?? {})) for (const id of ids) cite(id, 'tests/vectors/sp-proto-v1.json');

const manual = (r) => /^(Manual review|CI check)/i.test(r.planned);
const rows = { Must: [], Should: [], Could: [] };
for (const r of requirements) (rows[r.priority] ??= []).push(r);
let out = '# Requirement coverage\n\nGenerated by `tools/traceability/coverage.mjs` from [traceability.md](traceability.md) and the identifiers cited by the automated tests. Do not edit by hand.\n\n';
out += '| Priority | Requirements | Cited by automated tests | Manual review or CI check | Not yet verified |\n|---|---:|---:|---:|---:|\n';
for (const [priority, list] of Object.entries(rows)) {
  const automated = list.filter((r) => cited.has(r.id)).length;
  const manualOnly = list.filter((r) => !cited.has(r.id) && manual(r)).length;
  out += `| ${priority} | ${list.length} | ${automated} | ${manualOnly} | ${list.length - automated - manualOnly} |\n`;
}
const unknown = [...cited.keys()].filter((id) => !requirements.some((r) => r.id === id)).sort();
if (unknown.length > 0) out += `\nIdentifiers cited by tests but absent from the matrix: ${unknown.join(', ')}.\n`;
for (const priority of ['Must', 'Should', 'Could']) {
  const missing = (rows[priority] ?? []).filter((r) => !cited.has(r.id) && !manual(r));
  out += `\n## ${priority} requirements not yet verified by an automated test (${missing.length})\n\n`;
  if (missing.length === 0) {
    out += 'None.\n';
    continue;
  }
  out += '| ID | § | Summary | Planned test |\n|---|---|---|---|\n';
  for (const r of missing) out += `| ${r.id} | ${r.section} | ${r.summary} | ${r.planned} |\n`;
}
out += '\n## Requirements cited by automated tests\n\n| ID | Tests |\n|---|---|\n';
for (const r of requirements.filter((x) => cited.has(x.id))) out += `| ${r.id} | ${[...cited.get(r.id)].sort().map((f) => `\`${f}\``).join(', ')} |\n`;

const target = join(root, 'docs/coverage.md');
if (process.argv.includes('--check')) {
  if (readFileSync(target, 'utf8') !== out) {
    process.stderr.write('docs/coverage.md is out of date: run node tools/traceability/coverage.mjs\n');
    process.exit(1);
  }
} else {
  writeFileSync(target, out);
}
